print("   __")
print("  [ ]")
print(" /   \.")
print("/     \.") 
print("|     |")
print("|     |")
print("|     |")
print("\_____/",end = "")


print("/--------\.",end = "")
print("| °    °  |",end = "")
print("\_________/")

print("|__|")

print("       __C__")
print("     _|____|_")
print("   _|________|_")
print("  |____________|")

print("_____________")
print("|  JOURNAL  |")
print("|           |")
print("-------------")
print("|~~~~ |     |")
print("| ~~~ |     |")
print("| ~~~~~~~~  |")
print("| --------  |")
print("| --------  |")
print("|___________|")

print("Gas Station")
print(" __________")
print("/          \.")
print(" ----------")
print(" | []     |")
print(" | [^     |")
print(" | []     |")
print(" ------------------------")

print("CEMITÉRIO DE MACNHESTER")
print("   __")
print("__| |__")
print("|__  __|")
print("  | |")
print("  | |")
print("~~|~~~~~~")
print("~~ ~ ~~~~~~")
print("~~~~~~~~~~~~~~")

print("       ________")
print(" _____/ __|_____\.")
print("/         |°     |")
print("---(*) ----(*) --")
